# -*- coding: utf-8 -*-
"""CORAL -resnet 50

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SmbmJFIsGeQg2iuOc7ApWUlmg3UHOUIo
"""

! pip install torchinfo torchvision

# Commented out IPython magic to ensure Python compatibility.
!git clone https://gitlab.com/arthurpessa/ordinal_nets_lc.git
# %cd ordinal_nets_lc

# Commented out IPython magic to ensure Python compatibility.
# %ls 'lc_pictures/8cb(segunda ordem)/8CB_2/'

import os
import torch
from torchvision import transforms
from PIL import Image
folder_1 = "lc_pictures/8cb(segunda ordem)/8CB_2/"

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Resize((224, 224))
])


def load_images_from_folder(folder_path):
    image_files = [x for x in os.listdir(folder_path) if x.endswith('.jpeg') or x.endswith('.jpg')]
    images = []
    for file in image_files:
        img_path = os.path.join(folder_path, file)
        image = Image.open(img_path)
        image = transform(image)
        images.append(image)
    return torch.stack(images)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

images_1 = load_images_from_folder(folder_1).to(device)

import pandas as pd
folder_1 = "lc_pictures/8cb(segunda ordem)/8CB_2/"
image_paths = [f for f in os.listdir(folder_1) if f.endswith(".jpeg")]


df = pd.DataFrame({
    "image_path": [os.path.join(folder_1, f) for f in image_paths],
    "temperature": [float(f.replace(".jpeg", "")) for f in image_paths]
})

def assign_label(temp):
    if temp >= 35:
        return 0
    elif 25 <= temp < 35:
        return 1
    elif temp < 25:
        return 2

df["label"] = df["temperature"].apply(assign_label)

df.head()

def load_images_and_temperatures(load_path, image_size=224):
    """
    Loads images and their corresponding temperatures from filenames.
    Returns preprocessed images (for ResNet) and temperatures as float labels.
    """
    image_paths = sorted(glob.glob(os.path.join(load_path, "*.jpeg")))
    cut_index = len(load_path) + 1

    transform = transforms.Compose([
        transforms.Resize((image_size, image_size)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225])
    ])

    images = []
    temperatures = []
    for path in image_paths:
        img = Image.open(path).convert('RGB')
        images.append(transform(img))
        temp = float(path[cut_index:-5])
        temperatures.append(temp)

    return images, temperatures

import torch
import torch.nn as nn
from torchvision.models import resnet50

class CoralResNet50(nn.Module):
    def __init__(self, num_classes):
        super(CoralResNet50, self).__init__()
        self.backbone = resnet50(pretrained=True)
        self.backbone.fc = nn.Identity()
        self.fc = nn.Linear(2048, num_classes - 1)

    def forward(self, x):
        features = self.backbone(x)
        logits = self.fc(features)
        return logits

def coral_loss(logits, levels, importance_weights=None):
    """
    Computes CORAL loss.
    """
    val = - torch.sum(
        (levels * torch.log(torch.sigmoid(logits)) + (1 - levels) * torch.log(1 - torch.sigmoid(logits))),
        dim=1
    )
    if importance_weights is not None:
        val = val * importance_weights
    return torch.mean(val)

def temperatures_to_levels(temps, class_thresholds):
    """
    Converts temperature values to ordinal levels (binary vector of K-1).
    """
    levels = []
    for t in temps:
        level = [1 if t > thresh else 0 for thresh in class_thresholds[:-1]]
        levels.append(level)
    return torch.tensor(levels, dtype=torch.float)

def logits_to_levels(logits):
    """
    Converts logits into predicted ordinal levels.
    Each level is 1 if sigmoid(logit) > 0.5 else 0.
    """
    probas = torch.sigmoid(logits)
    return (probas > 0.5).int()

def levels_to_class_index(levels):
    """
    Converts binary levels into class index (temperature bin index).
    """
    return torch.sum(levels, dim=1)

def predict_temperature_from_logits(logits, class_thresholds):
    """
    Full pipeline: logits -> levels -> class index -> temperature.
    """
    levels = logits_to_levels(logits)
    class_indices = levels_to_class_index(levels)
    temperatures = class_index_to_temperature(class_indices, class_thresholds)
    return temperatures

import torch
from torch.utils.data import Dataset
from PIL import Image
import numpy as np

class TemperatureOrdinalDataset(Dataset):
    def __init__(self, dataframe, transform=None, num_classes=None):
        self.df = dataframe
        self.transform = transform
        self.num_classes = num_classes or self.df['label'].nunique()

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img_path = row['image_path']
        image = Image.open(img_path).convert("RGB")

        if self.transform:
            image = self.transform(image)

        label = int(row['label'])
        levels = torch.tensor([1]*label + [0]*(self.num_classes - 1 - label), dtype=torch.float32)

        return image, levels

from torchvision import transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

dataset = TemperatureOrdinalDataset(df, transform=transform)
dataloader = DataLoader(dataset, batch_size=16, shuffle=True)

import torch.nn.functional as F

def coral_loss(logits, levels, importance_weights=None):
    """
    logits: shape (batch_size, num_classes - 1)
    levels: same shape, binary 1 if class >= k
    """
    val = F.binary_cross_entropy_with_logits(logits, levels, weight=importance_weights, reduction='mean')
    return val

class CoralResNet50(nn.Module):
    def __init__(self, num_classes=3):
        super(CoralResNet50, self).__init__()
        self.backbone = resnet50(pretrained=True)
        in_features = self.backbone.fc.in_features
        self.backbone.fc = nn.Identity()
        self.coral_head = nn.Linear(in_features, num_classes - 1)

    def forward(self, x):
        x = self.backbone(x)
        logits = self.coral_head(x)
        return logits

num_classes = df['label'].nunique()
model = CoralResNet50(num_classes=num_classes).to(device)

model = CoralResNet50(num_classes=num_classes).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

for images, levels in dataloader:
    images = images.to(device)
    levels = levels.to(device)

    optimizer.zero_grad()
    logits = model(images)
    loss = coral_loss(logits, levels)
    loss.backward()
    optimizer.step()

import matplotlib.pyplot as plt

def train_model(model, dataloader, optimizer, num_epochs=10, device='cuda'):
    model.train()
    loss_history = []

    for epoch in range(num_epochs):
        epoch_loss = 0.0
        for images, levels in dataloader:
            images = images.to(device)
            levels = levels.to(device)

            optimizer.zero_grad()
            logits = model(images)
            loss = coral_loss(logits, levels)
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item() * images.size(0)

        avg_loss = epoch_loss / len(dataloader.dataset)
        loss_history.append(avg_loss)
        print(f"Epoch [{epoch+1}/{num_epochs}] - Loss: {avg_loss:.4f}")

    return loss_history

model = CoralResNet50(num_classes=num_classes).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-5)

losses = train_model(model, dataloader, optimizer, num_epochs=100, device=device)


plt.figure(figsize=(8,5))
plt.plot(losses, marker='o')
plt.title("Training Loss over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.grid(True)
plt.show()

def coral_logits_to_label(logits):
    probas = torch.sigmoid(logits)
    return torch.sum(probas > 0.5, dim=1)


model.eval()
with torch.no_grad():
    for images, levels in dataloader:
        images = images.to(device)
        logits = model(images)
        preds = coral_logits_to_label(logits).cpu().numpy().astype(float)
        true_labels = torch.sum(levels, dim=1).cpu().numpy()

        print("Predicted:", preds)
        print("Ground Truth:", true_labels)
        break

def class_index_to_temperature(class_indices, class_thresholds):
    """
    Converts class indices to midpoints of corresponding temperature bins.
    """
    bin_centers = 0.5 * (class_thresholds[:-1] + class_thresholds[1:])
    bin_centers = torch.tensor(bin_centers)
    return bin_centers[class_indices]

import numpy as np
import torch
from sklearn.metrics import mean_absolute_error

def predict_temperature_from_logits(logits, class_thresholds):
    """
    Convert ordinal logits into class labels and then map to temperature using thresholds.
    """
    # logits shape: (batch_size, num_classes - 1)
    probas = torch.sigmoid(logits)  # convert logits to probabilities
    pred_labels = torch.sum(probas > 0.5, dim=1)  # ordinal regression decoding
    pred_labels = pred_labels.cpu().numpy()

    # Map labels to temperature values using class thresholds
    pred_temps = []
    for label in pred_labels:
        if label == 0:
            pred_temps.append(class_thresholds[0])
        elif label == len(class_thresholds):
            pred_temps.append(class_thresholds[-1])
        else:
            # interpolate between thresholds
            temp = (class_thresholds[label - 1] + class_thresholds[label]) / 2
            pred_temps.append(temp)

    return np.array(pred_temps)

def evaluate_real_temperatures(model, dataloader, class_thresholds, device='cuda'):
    model.eval()
    pred_temps = []
    true_temps = []

    with torch.no_grad():
        for images, levels, real_temp in dataloader:
            images = images.to(device)
            logits = model(images)

            # Predict temperature from logits
            predicted = predict_temperature_from_logits(logits, class_thresholds)
            pred_temps.extend(predicted)
            true_temps.extend(real_temp.numpy())

    # Convert to float arrays
    true_temps = np.array(true_temps, dtype=np.float32)
    pred_temps = np.array(pred_temps, dtype=np.float32)

    # Compute metrics
    mae = mean_absolute_error(true_temps, pred_temps)
    rae = np.sum(np.abs(true_temps - pred_temps)) / \
          np.sum(np.abs(true_temps - np.mean(true_temps)))

    print(f"\nReal Temp Evaluation:\nMAE: {mae:.4f}°C\nRAE: {rae:.4f}")
    return mae, rae

class_thresholds = [25, 30, 35, 40]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

evaluate_real_temperatures(model, val_loader, class_thresholds, device=device)